# Generated by Django 2.0 on 2018-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('topic', models.TextField()),
                ('rw', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MqttUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('super_user', models.BooleanField(default=False)),
            ],
        ),
    ]
