# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c26272d-411f-4808-bb48-4c859182a410'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ac4d353-4200-434a-bb20-685dd30f7ce1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0711b30-dd1d-460e-ac77-0301bd307fff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
