# Generated by Django 2.0 on 2018-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180810_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='showname',
            field=models.CharField(default='nonoe', max_length=200),
            preserve_default=False,
        ),
    ]
