# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180102_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b34e6e4b-8cb5-48d8-af14-61ea67648c70'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bd0e9a8-e607-49da-9f57-bbad25263575'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8cda398-dfab-435c-93ab-55e87a1fcf7e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
