# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180102_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fce6e0d-d283-4f00-bf7f-569a35c3fbd7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f562ddc-c51d-4dbd-998b-ad1df402ba4a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d15fd4d9-cb63-4fa6-af18-b5bddd281404'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
