# Generated by Django 2.0 on 2018-11-06 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180810_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('double_data', models.FloatField(blank=True, default=None, null=True)),
                ('int_data', models.BigIntegerField(blank=True, default=None, null=True)),
                ('bool_data', models.NullBooleanField(default=None)),
                ('string_data', models.TextField(blank=True, default=None, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='project.Sensor')),
            ],
        ),
    ]
