# Generated by Django 2.0 on 2018-11-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(default='string', max_length=100),
        ),
    ]
